# Generated by Django 3.2.4 on 2022-09-10 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('person_type', models.IntegerField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/pictures')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('is_collector', models.BooleanField(default=True)),
                ('is_productor', models.BooleanField(default=False)),
                ('dni', models.CharField(max_length=20)),
                ('contador_actualizar', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Recolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('plastic', models.BooleanField(default=False)),
                ('plastic_price', models.BigIntegerField(default=False)),
                ('cardboard', models.BooleanField(default=False)),
                ('cardboard_price', models.BigIntegerField(default=False)),
                ('paper', models.BooleanField(default=False)),
                ('paper_price', models.BigIntegerField(default=False)),
                ('glass', models.BooleanField(default=False)),
                ('glass_price', models.BigIntegerField(default=False)),
                ('trash', models.BooleanField(default=False)),
                ('trash_price', models.BigIntegerField(default=False)),
                ('metal', models.BooleanField(default=False)),
                ('metal_price', models.BigIntegerField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
