# Generated by Django 3.2.4 on 2022-10-14 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contador_actualizar',
            new_name='update_counter',
        ),
        migrations.CreateModel(
            name='VProductorRecolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoriza_recolector', models.CharField(max_length=1)),
                ('autoriza_productor', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('productor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productor_v', to=settings.AUTH_USER_MODEL)),
                ('recolector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recolector_v', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('productor', 'recolector')},
            },
        ),
    ]
