# Generated by Django 3.2.4 on 2022-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
