# Generated by Django 3.2.4 on 2022-06-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
