# Generated by Django 3.2.4 on 2022-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canecas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caneca',
            name='cardboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caneca',
            name='glass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caneca',
            name='metal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caneca',
            name='paper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caneca',
            name='plastic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caneca',
            name='trash',
            field=models.IntegerField(default=0),
        ),
    ]
