# Generated by Django 3.2.4 on 2022-06-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canecas', '0004_alter_caneca_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caneca',
            name='n_peticiones',
            field=models.BigIntegerField(default=0),
        ),
    ]
