# Generated by Django 3.2.4 on 2022-02-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('definicion', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=1200)),
                ('recolector_disponible', models.BooleanField()),
            ],
        ),
    ]
